# Autogenerated wrapper script for eckit_jll for powerpc64le-linux-gnu-cxx03
export eckit, geometry, info, linalg, maths, mpi, option, sql, version, web

JLLWrappers.@generate_wrapper_header("eckit")
JLLWrappers.@declare_library_product(eckit, "libeckit.so")
JLLWrappers.@declare_library_product(geometry, "libeckit_geometry.so")
JLLWrappers.@declare_library_product(linalg, "libeckit_linalg.so")
JLLWrappers.@declare_library_product(maths, "libeckit_maths.so")
JLLWrappers.@declare_library_product(mpi, "libeckit_mpi.so")
JLLWrappers.@declare_library_product(option, "libeckit_option.so")
JLLWrappers.@declare_library_product(sql, "libeckit_sql.so")
JLLWrappers.@declare_library_product(web, "libeckit_web.so")
JLLWrappers.@declare_executable_product(info)
JLLWrappers.@declare_executable_product(version)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        eckit,
        "lib/libeckit.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        geometry,
        "lib/libeckit_geometry.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        linalg,
        "lib/libeckit_linalg.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        maths,
        "lib/libeckit_maths.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        mpi,
        "lib/libeckit_mpi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        option,
        "lib/libeckit_option.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        sql,
        "lib/libeckit_sql.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        web,
        "lib/libeckit_web.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        info,
        "bin/eckit-info",
    )

    JLLWrappers.@init_executable_product(
        version,
        "bin/eckit-version",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
